name: utopia_di
description: Light & Fast Dart Dependency Injection library. Easy to use and powerful for all kinds of needs, with no external dependencies.
version: 0.0.2
repository: https://github.com/utopia-dart/utopia_di

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
