name: utopia_di
description: Light & Fast Dart Dependency Injection library. Easy to use and powerful for all kinds of needs, with no external dependencies.
version: 0.0.3
repository: https://github.com/utopia-dart/utopia_di

environment:
  sdk: '>=2.19.2 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
